config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, except: [:destroy, :edit, :update] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, :movie_id, presence: true
  validates :list_id, uniqueness: { scope: :movie_id, message: "A bookmark for this movie in this list already exists" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    list = Bookmark.find_by(list_id: params[:list_id])
    Bookmark.find(params[:id]).destroy
    redirect_to list_path(list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      redirect_to lists_new_path
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h2>New Bookmark</h2>
<%= simple_form_for [@list,@bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<h2>All Lists</h2>
<%= link_to "Add new list", new_list_path %>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>Create a new list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<%# placeholder for in li when movie done "link_to movie.title, movie_path(movie)"" %>
<h1><%= @list.name %></h1>
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><%= bookmark.comment %> <%= bookmark.movie.title %> <%=link_to "🗑", list_bookmark_path(bookmark, @list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
  <% end %>
</ul>
<%= link_to "Add a movie to the list", new_list_bookmark_path(@list) %>
<%= link_to "Back to all lists", lists_path %>